### ISSUE TITLE
New items are in a state of "Published, but is Pending".

### ISSUE THREAD

**Issue by shkodskihk** [asikart/quickicons#16] opened 2015-01-15 15:35 UTC
1) After you create in the table of the component of the new element (new icon) its state: "Published, but is Pending". What could be the reason?

2) I can not delete them: these items are not removed: if you try to move them to the trash - nothing happens, they remain in the same place.

Screenshots:
http://i.imgur.com/0B1k7sq.png

[V. 2.0.1 / Joomla!, 3.3.6.]

**Comment by asika32764** [comment] 2015-01-15 16:44
It is a known bug which caused by Windwalker Framework. Please wait for next release.

Thank you.

**Comment by shkodskihk** [comment] 2015-01-15 16:55
Thank you for your support.

Three new elements I still managed to create.  The fourth and further - in a state of "pending". If it does not create a new icon - the component will lose its value.

How I can fix yourself this situation?

**Comment by asika32764** [comment] 2015-01-15 17:51
You can try 1.1.x stable first

We will fix this bug soon

shkodskihk <notifications@github.com> 於 2015年1月16日 星期五寫道：

> Thank you for your support.
>
> Three new elements I still managed to create. The fourth and further - in
> a state of "pending". If it does not create a new icon - the component will
> lose its value.
>
> How I can fix yourself this situation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/quickicons/issues/16#issuecomment-70118337>.
>


-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by asika32764** [comment] 2015-01-18 13:23
[2.0.2](https://github.com/asikart/quickicons/releases/tag/2.0.2) has released, this issue should be fixed. Please try it.

**Closed** 2015-03-11 05:35 UTC
Labels: bug, Resolved
